import type { CSSProperties } from "react";

/** Co-located styles for PrBriefSection and its presentational children. */
export const s = {
  stack: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  loadingStack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  cardTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
    marginBottom: 12,
  } satisfies CSSProperties,
  emptyWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    textAlign: "center",
    padding: "12px 0",
  } satisfies CSSProperties,
  emptyTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  emptyBody: { fontSize: 13, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  actionsRow: { display: "flex", alignItems: "center", gap: 8, marginTop: 8 } satisfies CSSProperties,
  banner: {
    display: "flex",
    gap: 16,
    alignItems: "flex-start",
    padding: 18,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  bannerMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  bannerTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  bannerLabel: { fontSize: 13, fontWeight: 700, color: "var(--text-muted)" } satisfies CSSProperties,
  verdictLabel: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  hintBtn: {
    display: "inline-grid",
    placeItems: "center",
    padding: 0,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "help",
  } satisfies CSSProperties,
  summary: {
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    margin: "8px 0 0",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  meta: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 10,
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  scoreCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
    flexShrink: 0,
  } satisfies CSSProperties,
  scoreLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 13,
  } satisfies CSSProperties,
  noticeText: { flex: 1 } satisfies CSSProperties,
  link: { color: "inherit", textDecoration: "underline", fontWeight: 600 } satisfies CSSProperties,
  missing: {
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--text-secondary)",
    fontSize: 13,
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    margin: 0,
    padding: 0,
    listStyle: "none",
  } satisfies CSSProperties,
  listItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
  docs: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  pickerWrap: { position: "relative", display: "inline-block" } satisfies CSSProperties,
  pickerPanel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    zIndex: 20,
    width: 380,
    maxHeight: 360,
    overflowY: "auto",
    textAlign: "left",
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  pickerRow: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  pickerReason: { fontSize: 12, color: "var(--text-muted)", marginLeft: 26 } satisfies CSSProperties,
  pickerTokens: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  searchResult: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
