import type { CSSProperties } from "react";

export const s = {
  row: {
    borderRadius: 8,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    overflow: "hidden",
  } satisfies CSSProperties,
  toggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "9px 12px",
    background: "transparent",
    border: 0,
    color: "var(--text-primary)",
    cursor: "pointer",
    textAlign: "left",
    fontSize: 13.5,
  } satisfies CSSProperties,
  name: { fontWeight: 600, overflowWrap: "anywhere" } satisfies CSSProperties,
  count: {
    marginLeft: "auto",
    fontSize: 12.5,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  body: { padding: "0 12px 12px 30px" } satisfies CSSProperties,
  callers: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    margin: 0,
    padding: "0 0 0 10px",
    listStyle: "none",
    borderLeft: "1px solid var(--border-strong)",
  } satisfies CSSProperties,
  caller: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  callerLink: { color: "inherit", textDecoration: "none" } satisfies CSSProperties,
  chipGroup: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  } satisfies CSSProperties,
  endpointChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "2px 8px",
    borderRadius: 6,
    fontSize: 12,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  cronChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "2px 8px",
    borderRadius: 6,
    fontSize: 12,
    background: "var(--warn-bg)",
    color: "var(--warn)",
  } satisfies CSSProperties,
} as const;
