import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard. */
export const s = {
  card: (accepted: boolean, dimmed: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 232px",
    gap: 22,
    padding: "18px 22px 18px 24px",
    borderRadius: 12,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${accepted ? "var(--ok)" : "var(--border-strong)"}`,
    background: "var(--bg-surface)",
    opacity: dimmed ? 0.7 : 1,
  }),
  main: { minWidth: 0, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  ruleRow: { display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  rule: { fontSize: 16, fontWeight: 700, fontStyle: "italic", lineHeight: 1.35 } satisfies CSSProperties,
  categoryTag: {
    fontSize: 11.5,
    padding: "2px 8px",
    borderRadius: 99,
    border: "1px solid var(--border)",
    color: "var(--text-secondary)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rationale: { fontSize: 13, color: "var(--text-secondary)", marginTop: -4 } satisfies CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-primary)",
    overflow: "hidden",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  evidencePath: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "inherit",
    textDecoration: "none",
  } satisfies CSSProperties,
  iconBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    borderRadius: 5,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "12px 14px",
    fontSize: 12.5,
    lineHeight: 1.6,
    whiteSpace: "pre",
    overflowX: "auto",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  meta: { display: "flex", alignItems: "center", gap: 12, fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  bar: { width: 140 } satisfies CSSProperties,
  pct: { color: "var(--text-secondary)" } satisfies CSSProperties,
  found: { marginLeft: 6 } satisfies CSSProperties,
  actions: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  form: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  formActions: { display: "flex", gap: 8, justifyContent: "flex-end" } satisfies CSSProperties,
} as const;
