import type { CSSProperties } from "react";

export const s = {
  heading: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 10px",
  } satisfies CSSProperties,
  list: { display: "flex", gap: 8, flexWrap: "wrap", listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  empty: { fontSize: 13.5, color: "var(--text-secondary)", margin: 0 } satisfies CSSProperties,
  details: {
    marginTop: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  explanation: { fontSize: 12.5, lineHeight: 1.55, color: "var(--text-secondary)", margin: 0 } satisfies CSSProperties,
  refs: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 8 } satisfies CSSProperties,
  refLink: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "pointer",
    fontSize: 11.5,
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  pill: { display: "inline-flex", alignItems: "stretch", borderRadius: 7, overflow: "hidden" } satisfies CSSProperties,
  pillMain: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    alignItems: "flex-start",
    padding: "5px 9px",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  pillTitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  pillRef: { fontSize: 10.5, color: "var(--accent-text)" } satisfies CSSProperties,
  chevron: {
    display: "grid",
    placeItems: "center",
    width: 26,
    border: "none",
    borderLeft: "1px solid var(--border)",
    background: "transparent",
    cursor: "pointer",
  } satisfies CSSProperties,
} as const;
