import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillDrawer. */
export const s = {
  fileRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  fileName: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  status: { fontSize: 13, color: "var(--text-muted)", marginTop: 10 } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)", marginTop: 10 } satisfies CSSProperties,
  previewWrap: { marginTop: 20, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  previewTitle: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  bodyPre: {
    margin: 0,
    padding: "12px 14px",
    fontSize: 12.5,
    lineHeight: 1.55,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
    borderRadius: 7,
    whiteSpace: "pre-wrap",
    maxHeight: 220,
    overflow: "auto",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  listCard: {
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  listTitle: {
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  listItem: { fontSize: 12.5, color: "var(--text-secondary)", lineHeight: 1.6 } satisfies CSSProperties,
  untrustedNotice: {
    display: "flex",
    gap: 8,
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    borderRadius: 7,
    padding: "10px 12px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  footer: { display: "flex", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
} as const;
