import type { CSSProperties } from "react";

/** Co-located styles for IntentCard + its notice/alert rows. */
export const s = {
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  title: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  headerBadges: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginLeft: "auto",
  } satisfies CSSProperties,
  summary: {
    fontSize: 14,
    color: "var(--text-secondary)",
    lineHeight: 1.55,
    fontStyle: "italic",
    margin: "0 0 14px",
  } satisfies CSSProperties,
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 20,
    marginBottom: 14,
  } satisfies CSSProperties,
  notices: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 14,
  } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--text-secondary)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  noticeIcon: { color: "var(--warn)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  sourcesList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginBottom: 14,
  } satisfies CSSProperties,
  sourceItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sourceKind: { color: "var(--text-muted)" } satisfies CSSProperties,
  sourceReason: { color: "var(--warn)", marginLeft: 4 } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    paddingTop: 12,
    marginTop: 2,
    borderTop: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskSlot: {
    marginTop: 14,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerSpacer: { flex: 1 } satisfies CSSProperties,
  alert: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 13,
  } satisfies CSSProperties,
  alertLink: { color: "inherit", textDecoration: "underline", fontWeight: 600 } satisfies CSSProperties,
  loadingStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  compactActions: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: 10,
  } satisfies CSSProperties,
  /** Visually hidden, still announced by screen readers (live status for "detecting"). */
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
} as const;
